services:
  postgis:
    image: postgis/postgis:17-3.5-alpine
    environment:
      POSTGRES_USER: reitti
      POSTGRES_PASSWORD: reitti
      POSTGRES_DB: reittidb
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reitti -d reittidb"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
      - "1883:1883" #MQTT port
    environment:
      RABBITMQ_DEFAULT_USER: reitti
      RABBITMQ_DEFAULT_PASS: reitti
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
  mqtt:
    image: eclipse-mosquitto:2.0.18
    ports:
      - "1884:1883"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./docker/redis-dev/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "-u", "redis://reitti:reitti@localhost:6379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
#  photon:
#    image: rtuszik/photon-docker:1.3.0
#    environment:
#      - UPDATE_STRATEGY=PARALLEL
#      - REGION=de
#    ports:
#      - "2322:2322"
#    volumes:
#      - photon-data:/photon/data
  ot-recorder:
    image: owntracks/recorder:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - OTR_HOST=rabbitmq
      - OTR_USER=reitti
      - OTR_PASS=reitti
    ports:
      - "8083:8083"
    volumes:
      - ot-recorder-data:/store
  tile-cache:
    build: ./docker/tiles-cache
    restart: unless-stopped
    ports:
      - "8084:80"
    volumes:
      - tile-cache-data:/var/cache/nginx
volumes:
  postgis-data:
  redis-data:
  rabbitmq-data:
  photon-data:
  ot-recorder-data:
  tile-cache-data:
