# Data management configuration
reitti.data-management.enabled=true
# Enable hostname verification before deleting all data (true/false)
reitti.data-management.delete-all.hostname-verification.enabled=false

logging.level.com.dedicatedcode.reitti=DEBUG
logging.level.com.dedicatedcode.reitti.service.processing.UnifiedLocationProcessingService = TRACE
logging.level.com.dedicatedcode.reitti.controller.api.LocationDataApiController = TRACE

reitti.geocoding.photon.base-url=http://localhost:2322

reitti.import.batch-size=10000

spring.thymeleaf.cache=false

reitti.server.advertise-uri=http://localhost:8080

reitti.ui.tiles.cache.url=http://localhost:8084

reitti.security.local-login.disable=false

reitti.process-data.refresh-views.schedule=0 * * * * *

reitti.storage.path=data/

reitti.h3.enabled=true

#server.servlet.context-path=/reitti

#reitti.panoramax.base-url=

spring.data.redis.username=reitti
spring.data.redis.password=reitti
spring.data.redis.database=0
spring.cache.redis.key-prefix=reitti: