package com.dedicatedcode.reitti.service.jobs;

public enum JobType {
    GPS_IMPORT,
    GPS_INGESTION,
    GPX_IMPORT,
    GOOGLE_TIMELINE_IMPORT,
    GEOJSON_IMPORT,
    FIT_FILE_IMPORT,
    OWNTRACKS_IMPORT,
    VISIT_TRIP_DETECTION,
    REVERSE_GEOCODE,
    LOCATION_PROCESSING,
    DATA_RECALCULATION,
    RECALCULATION,
    LOCATION_DATA_CLEANUP,
    MANUAL_MODIFICATION,
    TIMELINE_STITCHING,
    H3_RECALCULATION,
    H3_CELL_UPDATE,
}
