CREATE TABLE random_cities
(
    name      TEXT PRIMARY KEY,
    latitude  DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    reason    TEXT NOT NULL
);

INSERT INTO random_cities (name, latitude, longitude, reason)
VALUES ('Tokyo', 35.6895, 139.6917,
        'Tokyo Skytree - The tallest tower in the world, symbolizing the city''s modernity. (Pop: ~37.5M)'),
       ('Delhi', 28.6129, 77.2295,
        'Red Fort - A 17th-century Mughal fortress representing the city''s deep historical roots. (Pop: ~32.9M)'),
       ('Shanghai', 31.2304, 121.4737,
        'The Bund - A famous waterfront with Art Deco buildings, showcasing historical wealth. (Pop: ~28.9M)'),
       ('São Paulo', -23.5505, -46.6333,
        'Edifício Martinelli - An iconic early skyscraper representing the city''s rapid growth. (Pop: ~22.8M)'),
       ('Mexico City', 19.4326, -99.1332,
        'Palacio de Bellas Artes - A stunning cultural center, symbolizing Mexican art and history. (Pop: ~22.3M)'),
       ('Cairo', 30.0444, 31.2357,
        'Great Pyramid of Giza - The only surviving ancient wonder, located on the city''s edge. (Pop: ~22.2M)'),
       ('Dhaka', 23.8103, 90.4125,
        'Lalbagh Fort - A 17th-century Mughal fort, a key historical landmark. (Pop: ~22.0M)'),
       ('Mumbai', 19.0760, 72.8777,
        'The Gateway of India - An arch-monument commemorating the visit of a British monarch. (Pop: ~21.9M)'),
       ('Beijing', 39.9042, 116.4074,
        'Forbidden City - The imperial palace for 24 emperors, a symbol of ancient Chinese power. (Pop: ~21.3M)'),
       ('Osaka', 34.6937, 135.5023,
        'Osaka Castle - A landmark that was crucial in the unification of Japan. (Pop: ~19.1M)'),
       ('Karachi', 24.8607, 67.0011,
        'Mazar-e-Quaid - The mausoleum of Pakistan''s founder, a modern architectural icon. (Pop: ~16.8M)'),
       ('Buenos Aires', -34.6037, -58.3816,
        'Obelisco - A national monument at the heart of the city''s most important avenue. (Pop: ~15.6M)'),
       ('Chongqing', 29.4316, 106.9123,
        'Jiefangbei - The central business district, featuring a monument to the people''s liberation. (Pop: ~15.4M)'),
       ('Istanbul', 41.0082, 28.9784,
        'Hagia Sophia - A former church and mosque, now a museum, showcasing Byzantine grandeur. (Pop: ~15.2M)'),
       ('Kolkata', 22.5726, 88.3639,
        'Victoria Memorial - A large marble building dedicated to Queen Victoria. (Pop: ~14.9M)'),
       ('Manila', 14.5995, 120.9842,
        'Rizal Park - A large urban park dedicated to the Philippine national hero. (Pop: ~13.9M)'),
       ('Rio de Janeiro', -22.9068, -43.1729,
        'Christ the Redeemer - An Art Deco statue of Jesus, a global icon of the city. (Pop: ~13.6M)'),
       ('Tianjin', 39.3434, 117.3616,
        'Tianjin Eye - A 120-meter Ferris wheel built over a bridge, a unique landmark. (Pop: ~13.6M)'),
       ('Kinshasa', -4.4419, 15.2663,
        'Palais du Peuple - A large governmental and cultural complex dominating the skyline. (Pop: ~13.5M)'),
       ('Guangzhou', 23.1291, 113.2644,
        'Canton Tower - A prominent tower known for its unique architecture. (Pop: ~13.3M)'),
       ('Los Angeles', 34.0522, -118.2437,
        'Hollywood Sign - An iconic landmark representing the city''s entertainment industry. (Pop: ~12.8M)'),
       ('Shenzhen', 22.5431, 114.0579,
        'Shenzhen Bay Sports Center - A modern architectural complex symbolizing the city''s innovation. (Pop: ~12.5M)'),
       ('Lagos', 6.5244, 3.3792,
        'Third Mainland Bridge - One of the longest bridges in Africa, a vital artery for the megacity. (Pop: ~12.4M)'),
       ('Bangalore', 12.9716, 77.5946,
        'Vidhana Soudha - The seat of the state legislature of Karnataka, a grand example of neo-Dravidian architecture. (Pop: ~12.3M)'),
       ('Paris', 48.8566, 2.3522,
        'Eiffel Tower - The global cultural icon of France and a symbol of Paris. (Pop: ~11.1M)'),
       ('Bogotá', 4.7110, -74.0721,
        'Monserrate - A mountain that overlooks the city, featuring a historic church at its peak. (Pop: ~10.9M)'),
       ('Jakarta', -6.2088, 106.8456,
        'National Monument (Monas) - A 132-meter tall monument symbolizing the struggle for Indonesian independence. (Pop: ~10.8M)'),
       ('Chennai', 13.0827, 80.2707,
        'Marina Beach - The longest natural urban beach in India, a central recreational spot. (Pop: ~10.7M)'),
       ('Tehran', 35.6892, 51.3890,
        'Azadi Tower - A monument combining elements of Sassanid and Islamic architecture. (Pop: ~9.4M)'),
       ('Lima', -12.0464, -77.0428,
        'Plaza Mayor de Lima - The historic birthplace of the city, surrounded by colonial buildings. (Pop: ~9.1M)'),
       ('Bangkok', 13.7563, 100.5018,
        'Grand Palace - A complex of buildings at the heart of Bangkok, serving as the royal residence. (Pop: ~9.0M)'),
       ('London', 51.5074, -0.1278,
        'Big Ben - The iconic clock tower of the Palace of Westminster, a symbol of the UK. (Pop: ~9.0M)'),
       ('Ho Chi Minh City', 10.8231, 106.6297,
        'Notre-Dame Cathedral Basilica of Saigon - A neo-Romanesque cathedral, a major landmark. (Pop: ~8.9M)'),
       ('New York City', 40.7128, -74.0060,
        'Statue of Liberty - A universal symbol of freedom and democracy. (Pop: ~8.8M)'),
       ('Hyderabad', 17.3850, 78.4867,
        'Charminar - A monument and mosque built in 1591, a defining symbol of the city. (Pop: ~8.7M)'),
       ('Wuhan', 30.5928, 114.3055,
        'Yellow Crane Tower - A historic tower celebrated in Chinese poetry and art. (Pop: ~8.4M)'),
       ('Taipei', 25.0330, 121.5654,
        'Taipei 101 - A skyscraper with a distinctive pagoda design, a symbol of modern Taiwan. (Pop: ~8.3M)'),
       ('Chengdu', 30.5728, 104.0668,
        'Jinli Ancient Street - A bustling street showcasing traditional Sichuanese architecture and culture. (Pop: ~8.2M)'),
       ('Luanda', -8.8383, 13.2344,
        'Fortaleza de São Miguel - A 16th-century Portuguese fortress overlooking the city and bay. (Pop: ~8.1M)'),
       ('Moscow', 55.7558, 37.6173,
        'Red Square - The historic square at the heart of the city, surrounded by iconic buildings. (Pop: ~12.6M)'),
       ('Berlin', 52.5200, 13.4050,
        'Brandenburg Gate - A neoclassical monument that has become a symbol of German reunification. (Pop: ~3.7M)'),
       ('Lübeck', 53.8654, 10.6865,
        'Holstentor - A city gate that is one of the relics of the city''s medieval fortifications and a symbol of the city. (Pop: ~0.2M)');

UPDATE user_settings
SET home_lat = latitude,
    home_lng = longitude
FROM (SELECT latitude, longitude FROM random_cities ORDER BY random() LIMIT 1) as rc
WHERE home_lng IS NULL
  AND home_lat IS NULL;