-- 1. Create the Parent Table
CREATE TABLE staging_location_points
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    partition_key    TEXT                        NOT NULL,
    user_id          BIGINT REFERENCES users (id), -- Who uploaded it
    device_id        BIGINT REFERENCES devices (id),
    timestamp        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    geom             geometry(Point, 4326),
    elevation_meters DOUBLE PRECISION,
    accuracy_meters  DOUBLE PRECISION            NOT NULL,
    promoted         BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id, partition_key)
) PARTITION BY LIST (partition_key);

CREATE INDEX staging_location_geom_idx ON staging_location_points USING GIST (geom);

CREATE TABLE import_jobs
(
    id         UUID PRIMARY KEY,                  -- The Job ID we generate
    user_id    BIGINT REFERENCES users (id),      -- Who uploaded it
    type       VARCHAR(30),                       -- 'GPX_IMPORT', 'API_BATCH', 'MANUAL_ENTRY'
    status     VARCHAR(20) NOT NULL,              -- PARSING, AWAITING_PROMOTION, COMPLETED, FAILED
    file_name  VARCHAR(255),                      -- Original GPX name for the UI
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_import_jobs_status_age ON import_jobs (status, updated_at);

ALTER TABLE users ADD COLUMN last_data_modified_at TIMESTAMP WITH TIME ZONE;