CREATE TABLE raw_source_points AS
SELECT accuracy_meters,
       timestamp,
       user_id,
       geom,
       elevation_meters,
       NULL::bigint AS device_id,
       ignored,
       invalid
FROM raw_location_points
WHERE synthetic = FALSE;

-- 2. Add Identity and Constraints
ALTER TABLE raw_source_points
    ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

CREATE UNIQUE INDEX idx_raw_source_upsert_target
    ON raw_source_points (user_id, timestamp, device_id)
    NULLS NOT DISTINCT;

-- 3. Add the Partial Indices (The secret to performance)
CREATE INDEX idx_raw_source_main_device
    ON raw_source_points (user_id, timestamp)
    WHERE device_id IS NULL;

CREATE INDEX idx_raw_source_external_devices
    ON raw_source_points (device_id, timestamp)
    WHERE device_id IS NOT NULL;


CREATE TABLE raw_location_points_new AS
SELECT rlp.id,
       rlp.accuracy_meters,
       rlp.timestamp,
       rlp.user_id,
       rlp.geom,
       rlp.processed,
       rlp.version,
       rlp.elevation_meters,
       rlp.synthetic,
       rlp.ignored,
       rlp.invalid,
       CASE
           WHEN rlp.synthetic = FALSE THEN rsp.id
           ELSE NULL
           END AS source_point_id
FROM raw_location_points rlp
         LEFT JOIN raw_source_points rsp
                   ON rlp.user_id = rsp.user_id
                       AND rlp.timestamp = rsp.timestamp;
-- 2. Drop the slow table and rename the new one
DROP TABLE raw_location_points CASCADE;
ALTER TABLE raw_location_points_new
    RENAME TO raw_location_points;

-- 1. Explicitly set the column to NOT NULL
ALTER TABLE raw_location_points
    ALTER COLUMN id SET NOT NULL;

-- 2. Now add the identity property
ALTER TABLE raw_location_points
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 3. Sync the sequence so the next ID starts after your current max
SELECT setval(
               pg_get_serial_sequence('raw_location_points', 'id'),
               (SELECT MAX(id) FROM raw_location_points)
       );

-- 3. Re-apply the DDL (Primary Key, Indices, Owner)
ALTER TABLE raw_location_points
    ADD PRIMARY KEY (id);
ALTER TABLE public.raw_location_points
    ALTER COLUMN invalid SET DEFAULT false,
    ALTER COLUMN invalid SET NOT NULL,
    ALTER COLUMN synthetic SET DEFAULT false,
    ALTER COLUMN synthetic SET NOT NULL,
    ALTER COLUMN ignored SET DEFAULT false,
    ALTER COLUMN ignored SET NOT NULL;

CREATE INDEX idx_raw_location_points_user_time_synthetic
    ON raw_location_points (user_id, timestamp, synthetic);

CREATE INDEX raw_location_points_processed
    ON raw_location_points (processed);

CREATE UNIQUE INDEX raw_location_points_user_id_timestamp_uindex
    ON raw_location_points (user_id, timestamp);

CREATE INDEX idx_covering_user_time
    ON raw_location_points (user_id, timestamp) INCLUDE (geom);

CREATE INDEX idx_raw_locations_user_timestamp_valid
    ON raw_location_points (user_id, invalid, ignored, timestamp)
    WHERE ((invalid = FALSE) AND (ignored = FALSE));

CREATE INDEX raw_location_points_user_id_processed_invalid_index
    ON raw_location_points (user_id, processed, invalid) INCLUDE (id, timestamp);

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- add time line override table
CREATE TABLE timeline_overrides
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint                      NOT NULL REFERENCES users (id),
    device_id  bigint                      NOT NULL REFERENCES devices (id),
    start_time timestamp(6) with time zone NOT NULL,
    end_time   timestamp(6) with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT NOW(),
    CONSTRAINT no_timeline_overlap EXCLUDE USING gist (
        user_id WITH =,
        TSTZRANGE(start_time, end_time) WITH &&
        )
);


CREATE OR REPLACE VIEW v_source_stream AS
WITH current_overrides AS (
    SELECT user_id, device_id, start_time, end_time
    FROM timeline_overrides
)
-- PART A: Points from specific overridden devices
SELECT
    rsp.id AS source_point_id, -- <--- Crucial back-link
    rsp.accuracy_meters,
    rsp.timestamp,
    rsp.user_id,
    rsp.geom,
    rsp.elevation_meters,
    rsp.device_id
FROM raw_source_points rsp
         JOIN current_overrides ov ON rsp.user_id = ov.user_id
    AND rsp.device_id = ov.device_id
    AND rsp.timestamp >= ov.start_time
    AND rsp.timestamp <= ov.end_time

UNION ALL

-- PART B: Points from the "Main" device (where no override exists)
SELECT
    rsp.id AS source_point_id, -- <--- Crucial back-link
    rsp.accuracy_meters,
    rsp.timestamp,
    rsp.user_id,
    rsp.geom,
    rsp.elevation_meters,
    rsp.device_id
FROM raw_source_points rsp
WHERE rsp.device_id IS NULL  -- This is our "Main" device convention
  AND NOT EXISTS (
    -- Only take the main point if there is NO override for this specific second
    SELECT 1
    FROM current_overrides ov
    WHERE ov.user_id = rsp.user_id
      AND rsp.timestamp >= ov.start_time
      AND rsp.timestamp <= ov.end_time
);
